version: '2.4'

services:
  jekyll:
    container_name: jekyll
    image: jekyll/jekyll
    restart: always
    volumes:
      - ${PWD}:/srv/jekyll
    command: jekyll serve
    ports : 
      - 4000:4000


# _config.yml 파일의 변동이 있을 경우
# command 에 bundle install && jekyll serve
